version: "3.7"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  caddy:
    image: abiosoft/caddy:no-stats
    volumes:
      - ./etc/Caddyfile:/etc/Caddyfile:ro
    ports:
      - "4000:2015"
  app:
    build:
      context: .
    volumes:
      - .:/app
      - elixir_build:/app/_build
      - elixir_deps:/app/deps
      - node_modules:/app/assets/node_modules
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      ERL_AFLAGS: "-kernel shell_history enabled"
      DATABASE_HOSTNAME: db
    command: sh -c "sleep infinity"
volumes:
  elixir_build:
  elixir_deps:
  node_modules:
